### ISSUE TITLE
Support environment variable slugs in JSON configuration file

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-vs-extension#10]
`CMakeSettings.json` has a syntax that supports this so we should try to use the same.  Described here: 

https://blogs.msdn.microsoft.com/vcblog/2017/08/14/cmake-support-in-visual-studio-customizing-your-environment/

**Comment by sboulema** [comment]
[Common macros for build commands and properties](https://docs.microsoft.com/en-us/cpp/ide/common-macros-for-build-commands-and-properties?view=vs-2017)
[About the the envionment variables such as $(INTDIR) in .vcproj](https://social.msdn.microsoft.com/Forums/en-US/6d1b9b23-3fb4-445c-afe9-92aa9ab0dee5/about-the-the-envionment-variables-such-as-intdir-in-vcproj?forum=msbuild)

Which ones of that list are the most important to support?

**Comment by solvingj** [comment]
On second look, I'm not actually able to find any examples of any of these files referencing any Visual Studio variables. I see lots of references using their macro syntax like `${workspaceHash}` but none actually referencing visual studio variables.  I'm going to ask the MSVC team about it. I may have been incorrect. 

I'm asking the MSVC team about it now.  Until I get a response, skip this.

**Comment by solvingj** [comment]
Ok, so this issue is still valid.  In the world of `CMake` integration, the `CMakeSettings.json` effectively defines all the normal visual studio variables, so there's no other "Visual Studio" variables to reference.  It does support environment variable references with macro:  `${env.PATH}` for example. (`env` just provides dict-like access to env vars`). 

This plugin is currently targeting integration with Visual Studio Solutions and Projects, so it would be desirable to support the Visual Studio macros in addition to the environment variables. Perhaps we could support a similar dict-like object such as: 

`${vs.XYZ}`

Where `XYZ` can be any visual studio project variable/macro.
