### ISSUE TITLE
cleanup the code

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-vs-extension#113]
we have many left-over from previous attempts of implementation.
we need to clean up these thing at some point.
these left-overs add unnecessary complexity to the code, and already caused some issues in the past (like in case of `.csi` magic).

things to review:
- https://github.com/conan-io/conan-vs-extension/blob/dev/Conan.VisualStudio/PackageListToolWindow.cs (some Windows we never show, planned to show the graph of packages?)
- https://github.com/conan-io/conan-vs-extension/blob/dev/Conan.VisualStudio/Services/InfobarService.cs (used to show bar at the top to offer solution reload, no longer needed)
- https://github.com/conan-io/conan-vs-extension/blob/dev/Conan.VisualStudio/Services/SolutionEventsHandler.cs (this one contains .csi code)
- https://github.com/conan-io/conan-vs-extension/blob/dev/Conan.VisualStudio/Services/VisualStudioDialogService.cs (used to display modal dialog boxes - now we use ErrorList and Output instead)

**Comment by jgsogo** [comment]
This is something we should do asap. I would vote to remove everything not needed/used and then to implement it again when we feel like it is the right moment to provide the functionality

**Comment by SSE4** [comment]
yeah, I also prefer to remove, unless some code relies on that - we always have Git history if we ever need to re-implement the things

**Comment by jgsogo** [comment]
I'm moving this issue to `next` milestone, we have got rid of enough dead code for `v1.2`. Thanks!

**Comment by SSE4** [comment]
@jgsogo I think this is basically done - we have identified and removed all unused/dead code.
next step is to complete https://github.com/conan-io/conan-vs-extension/pull/135

**Comment by jgsogo** [comment]
Ok, I'm sure there are still some functions we are not using or could be simplified, but let's close this issue, probably it is no longer a priority.

It has been nice 👌 

![image](https://user-images.githubusercontent.com/1406456/61474486-0d48cf80-a989-11e9-9547-a5f021c402e4.png)
