### ISSUE TITLE
Better error messaging for 

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-vs-extension#118]
When something fails, we get a 

```
Conan has returned exit code '1' while processing configuration
'Architecture... Please check file '...\.conan\conan_7101ceb0-d
ba-457c-bcb5-b9595a8619bb.log' for details
```

but nothing interesting is in that file 😖. At least we need to copy there all the output from the Conan execution.

**Comment by SSE4** [comment]
yeah, one of the reasons we don't capture stderr right now, only stdin:
https://github.com/conan-io/conan-vs-extension/blob/b2fe093ba7da40e9dfc624cb525253b9f5b5cef1/Conan.VisualStudio/Services/ConanService.cs#L128

**Comment by memsharded** [comment]
Yes, I am being badly affected by this one too, please try to prioritize if possible.
