### ISSUE TITLE
Can't use environment variables in options for paths

### ISSUE THREAD

**Issue by Gernatch** [conan-io/conan-vs-extension#138]
Causes "install" to do nothing:
![image](https://user-images.githubusercontent.com/7558344/61130458-b91f8600-a484-11e9-9bee-7bc39dee7d2c.png)

This is probably more of an enhancement request. Not sure if it was designed to allow environment variables.

**Comment by SSE4** [comment]
yeah, that's an enhancement, right now it doesn't support any environment variables

**Comment by jgsogo** [comment]
We may add a `configuration.Evaluate` call on this path like we did in #134 for the _install path_, it should be quite straightforward.

**Comment by SSE4** [comment]
@Gernatch to clarify - do you want Visual Studio macro definitions, like `${projectDir}`, `${outDir}`, etc ([full list](https://docs.microsoft.com/en-gb/cpp/build/reference/common-macros-for-build-commands-and-properties?view=vs-2019)), or system environment variables, like `$PATH`, `$TEMP`, etc?

**Comment by jgsogo** [comment]
Hi! I see a problem with this. In the next release we are [validating the path to the Conan executable](https://github.com/conan-io/conan-vs-extension/pull/136). If it depends on a VS macro or environment variable, this validation doesn't make sense: the environment may change and VS macros should be evaluated per configuration.

I really like to validate the path to `conan.exe` in the Options menu, we guarantee that it is going to be the same for all projects and configurations, but if the motivation to allow env/macros is strong enough I can change my mind.
