### ISSUE TITLE
Support tasks.vs.json for user-defined list of tasks available to plugin

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-vs-extension#14]
Opening this ticket following some discussion with @sboulema and msvc channel of slack. 

The `tasks.vs.json` is a straightforward, established and currently-supported mechanism for developers to define arbitrary tasks for use in Visual Studio. Currently, it's only supported in "Open Folder" workflows.  

This plugin intends to support "Open Project/Solution" workflows, so we don't have a first-class mechanism for using these tasks.  However, rather than try to define a completely separate specification for this plugin, we should just support parsing and using tasks from `tasks.vs.json`.  

After deciding that, it became clear that this functionality was generally useful and valuable, and should likely eventually be split off into a library on Nuget, and a separate extension.  Specifically, it could be very useful for enterprise organizations planning migrations from Visual Studio projects and workflows to CMake/OpenFolder projects and workflow.  Furthermore, the library would be very useful for any package manager projects wanting to implement behavior similar to what we're doing here. 

Also, with regard to the `onProjectLoad` functionality this plugin will use... now we can see the implementation of this against `tasks.vs.json` would also be generically useful, again in the package manager use case.  so, we will likely release this as a nuget library as well.

Once all this is implemented, we can return to building any remaining conan-specific-functionality (like menu items, etc) on top of it.

**Comment by sboulema** [comment]
More info on task.vs.json:
[Customize build and debug tasks for "Open Folder" development](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2017)

Creating a plugin for this sounds an awful lot similar to this extension:
[Command Task Runner](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.CommandTaskRunner)

**Comment by solvingj** [comment]
I’ve used that plugin. Again, by supporting the official format/spec, We can share the list/spec of conan commands between the Cmake native integration and this plugin for working with vs solutions.

**Comment by sboulema** [comment]
Ah yeah that would be a big plus

**Comment by solvingj** [comment]
After reviewing it again, I recall that another major deficiency was that it seemed to have no concept of the context with which it was being run.  I don't handles any of the VS variables like `configuration`, `arch`, `outdir`, which would be critical for any non-trivial use cases.
