### ISSUE TITLE
Output from stdout and stderr mixed

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-vs-extension#146]
We need to redirect stderr to stdout and capture only stdout to ensure that lines corresponding to them don't get mixed in the final output window or log file

**Comment by SSE4** [comment]
there are some suggestions to use `OutputDataReceived`:
https://stackoverflow.com/questions/52088894/when-run-a-program-in-c-all-the-messages-go-to-the-standard-output-but-the-st

**Comment by jgsogo** [comment]
Found this snippet: https://stackoverflow.com/a/38882348/837816, maybe it is enough.
