### ISSUE TITLE
Manage remotes

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-vs-extension#22]
add dialog page to the conan options to manage remotes:

- list remotes
- add remotes
- remove remotes
- allow to specify remote for `conan install`

**Comment by solvingj** [comment]
I was tempted by this idea several times also.  However, I came to believe these are actually the kinds of features that we should leave out of the extension for a long time, and possibly forever. I think they will become very time-consuming and difficult to support long-term, especially given the limited resources we have.  I think we should leave GUI menus for any non-essential Conan operations out of scope. (I mean essential for visual studio project integration).  I would like to build a systray-based application someday for that, but that's another topic.

**Comment by jdee** [comment]
I'd just like to be able to specify a `-r` option to the conan command via the extension. Otherwise in some cases I'm better off running `conan install` manually first to save time if I have binaries in my own remote that aren't in conan-center.

**Comment by jgsogo** [comment]
Hi! This issue has raised also for the [CLion plugin](https://github.com/conan-io/conan-clion-plugin) (private messages). I'm wondering if these plugins/extensions should add some kind of proxy to Conan configuration (remotes, some typical config vars,...). And it always arises the alternative of having a different window to configure Conan (systray, exec, server,...) so it can we the same for VS, CLion, cmd,... but it wouldn't have a native UX. I'm on the fence with this, IMHO I think it is easy enough 😕 

---

@jdee, for your request, there are two approaches I can think about:
 * adding an "install args" to configuration, like the CLion plugin does, but it is something that would apply to every project. 

   ![image](https://user-images.githubusercontent.com/1406456/64171173-47473580-ce52-11e9-902d-b20d47d582f0.png)

 * Using something like this approach (https://github.com/conan-io/conan-vs-extension/issues/171) to override the `install` command
