### ISSUE TITLE
Manage profiles

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-vs-extension#23]
add dialog page to manage conan profiles. profiles are complex, so at very least it would be nice to:

- list profiles
- add profiles
- remove profiles
- open profile for edit

editing individual profile entries is too much for the first implementation

**Comment by solvingj** [comment]
I have the same opinion on these features as I gave regarding remotes here: 
https://github.com/bincrafters/conan-vs-extension/issues/22#issuecomment-472441372
