### ISSUE TITLE
Add Chocolatey deployment

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-vs-extension#40]
Several popular extensions are setup to deploy to Chocolatey. I’ve asked why in gutter.com/extendvs 

Could be nice for testing early releases, as an alternative to GH releases. Slightly more automatable for a system administrator in an enterprise. It’s likely to be the preferred way to install at my organization.

https://github.com/madskristensen/AddAnyFile/blob/master/appveyor.yml

**Comment by SSE4** [comment]
seems like there is an option to deploy to NuGet, WDYT? (found it [here](https://help.appveyor.com/discussions/questions/3823-deploying-to-github-releases))

**Comment by solvingj** [comment]
Chocolatey is a nuget repo with specific support in appveyor. I will register the account on Chocolatey today and setup deployment.
