### ISSUE TITLE
CodeAnalysis

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-vs-extension#42]
there is C# [StyleCop](https://github.com/StyleCop/StyleCop) analyzer which may find some errors in our code, so it would be nice to set up it at some point and ensure complains are fixed

**Comment by solvingj** [comment]
I don’t object, but seems a low priority for such a small project.

**Comment by SSE4** [comment]
actually, [StyleCop](https://github.com/StyleCop/StyleCop) was abandoned some time ago and was replaced by [FxCop](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019), then it was integrated into [RoslynAnalyzers](https://github.com/dotnet/roslyn-analyzers), and finally it was integrated into the [VisualStudio CodeAnalysis](https://docs.microsoft.com/en-gb/visualstudio/code-quality/code-analysis-for-managed-code-overview?view=vs-2015)

**Comment by SSE4** [comment]
3 main analysers we may apply (just install into project via `NuGet Package Manager`):
- `Microsoft.CodeAnalyzers.FxCopAnalyzers` - security, performance and design issues
- `StyleCop.Analyzers` - code style
- `Microsoft.VisualStudio.SDK.Analyzers` - specific for VSIX and Visual Studio interfaces
there are many other analyzers available on NuGet, but let's start with these 3
