### ISSUE TITLE
Define policy to publish in Github and Open VSIX gallery

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-vs-extension#65]
Currently, we are only publishing the extension to MSFT marketplace (every successful build in ``master`` branch), but we can consider at least a couple more places:
 * Github: it is [deactivated](https://github.com/conan-io/conan-vs-extension/blob/e1cc09585273dd3b1b22764309b3f5d4b8732e71/appveyor.yml#L17)
 * Open VSIX Gallery: http://vsixgallery.com/ Quite easy to integrate using [these scripts](https://github.com/madskristensen/ExtensionScripts)

Anyway, not only the extension goes live in the VS marketplace

**Comment by SSE4** [comment]
also, we may want to publish to:
- chocolatey (https://github.com/conan-io/conan-vs-extension/issues/40)
- nuget
