### ISSUE TITLE
Error uninstalling extension (using menus inside VS IDE)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-vs-extension#67]
Although it could not be related to extension itself, as the problem reported by VS is _"Could not find file 'C:\USERS\<username>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_5ABB3F2E\EXTENSIONS\LICENSE.md'"_, it prevents the extension from being uninstalled...

 * Does it happens with other versions of VS? **Please, feedback!**

**Workaround:** command line uninstall:

```
VSIXInstaller.exe /uninstall:VSConanPackage.4d0379e2-2698-4e66-89de-6ead71165e9f
```

(find VSIXInstaller.exe at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE")

**Comment by SSE4** [comment]
yeah, it happens for me as well, and I have to delete lines manually
the problem it installs for all versions (2015, 2017, 2019), but if I uninstall it from the single place (e.g. 2015), it's still visible in 2017 and 2019. once I try to uninstall from 2017 as well, the issue appears.

**Comment by jgsogo** [comment]
Closed via https://github.com/conan-io/conan-vs-extension/pull/82
