### ISSUE TITLE
document developer set up

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-vs-extension#86]
need to document (in the README.MD or CONTRIBUTE.MD) how to prepare developer set up, with check boxes to check in Visual Studio installer, may be with screen-shots or GIFs.

**Comment by jgsogo** [comment]
We can/should/need to add this file (thanks to @solvingj for finding the link): https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/

> New in Visual Studio 2019: you can save these files as .vsconfig files in your solution root directory and when the solution (or solution directory) is opened, Visual Studio will automatically detect which components are missing and prompt you to install them.
