### ISSUE TITLE
[vs2017] Error loading in VS 2017

### ISSUE THREAD

**Issue by Gernatch** [conan-io/conan-vs-extension#87]
Installed from VS Marketplace. VS Version: `Microsoft Visual Studio 2017 version: 15.0.28307.489`

Get error upon load (launching VS). This is the log:

```
    <description>SetSite failed for package [VSConanPackage]Source: &apos;Conan.VisualStudio&apos; Description: Could not load file or assembly &apos;netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&apos;&#x000D;&#x000A;   at Conan.VisualStudio.Services.VisualStudioSettingsService.GetConanExecutablePath()&#x000D;&#x000A;   at Conan.VisualStudio.Services.SolutionEventsHandler..ctor(VSConanPackage package) in C:\projects\conan-vs-extension\Conan.VisualStudio\Services\SolutionEventsHandler.cs:line 24&#x000D;&#x000A;   at Conan.VisualStudio.VSConanPackage.&lt;InitializeAsync&gt;d__15.MoveNext() in C:\projects\conan-vs-extension\Conan.VisualStudio\VSConanPackage.cs:line 77&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
```

**Comment by SSE4** [comment]
I think this PR should fix that: https://github.com/conan-io/conan-vs-extension/pull/75
/cc @jgsogo

**Comment by jgsogo** [comment]
Hi! We need to find the root of this error before adding support for VS2015, although it will probably fix it because we are changing many requirements in that PR.

I think that this issue can be related with this one https://github.com/dotnet/standard/issues/328, the solution could be to add `NETStandard.Library.NETFramework`... but not sure, we should try to reproduce the error.

@Gernatch, having a look at that issue, I'm tempted to think that you are facing this error because the .NET Framework you have installed is too old. Can you check it and update it to 4.6.1 at least?

Thanks!

**Comment by SSE4** [comment]
@jgsogo I think problem is that we're using some frameworks from 15.4 version, but user is trying to use it in 15.0.

**Comment by Gernatch** [comment]
@jgsogo Sorry for the latest response. I have always been on the 4.6.1 .NET Framework since starting this. 
![image](https://user-images.githubusercontent.com/7558344/59196262-2d9c9780-8b5c-11e9-9562-b1e0e7fb0e3e.png)

Trying `NETStandard.Library.NETFramework`. More to follow.

**Comment by Gernatch** [comment]
I think my version wasn't properly reflected. Here is what I have in Help>About. 
![image](https://user-images.githubusercontent.com/7558344/59200379-119df380-8b66-11e9-8c2c-c0b8adefa52e.png)

**Comment by SSE4** [comment]
hi @Gernatch 
may you try to install the following build: https://ci.appveyor.com/project/ConanOrgCI/conan-vs-extension/builds/25177464/artifacts
and tell us if it helps
thank you

**Comment by lasote** [comment]
@Gernatch please, could you try if it works? Thanks!

**Comment by Gernatch** [comment]
@lasote Yes, will test today and update.

**Comment by Gernatch** [comment]
Update: This didn't work for me... however I'll provide some new information that I was not aware of. I assumed the laptop (which is managed by IT) had a consistent OS version across all laptops. However when trying to update to .NET 4.7.1, it failed because of OS incompatibility. Digging into this I discovered I'm on an OLD version of Windows 10.
![image](https://user-images.githubusercontent.com/7558344/59379321-51aad500-8d24-11e9-8677-3e8b718c649b.png)

So, it's possible that whatever dependencies I need might not work for my laptop. I don't expect this to be supported by this team here since even MS has dropped support for it. Unless it's worth exploring, I think we can consider this an OS issue, but I'll leave that up to you guys.

**Comment by SSE4** [comment]
similar issue: https://github.com/dotnet/roslyn/issues/25586
possible solutions:

- include NETStandard into VSIX
- downgrade NETStandard to 1.3

**Comment by SSE4** [comment]
hi @Gernatch 
I've prepared another build with another fix: https://ci.appveyor.com/project/ConanOrgCI/conan-vs-extension/builds/25255876/artifacts
could you possibly try to download and install this one and lemme know if it helps?
thank you.

**Comment by Gernatch** [comment]
This build works for me.

The change:
- convert .NET Standard Class libraries to .NET Framework Class libraries

**Comment by SSE4** [comment]
@Gernatch great news! thanks a lot for helping us with that.

**Comment by Gernatch** [comment]
@SSE4 Anytime. Excited to see this thing coming together. Thanks for the help.

**Comment by Gernatch** [comment]
@SSE4 Any idea how old of a .net framework version can be used? Some of my teams here are on 4.5.X. Thanks!

**Comment by SSE4** [comment]
right now it's 4.6.1. I need to check, but I believe we can try to lower to 4.5, I doubt we use any specific features from 4.6.1. there are might be problems with 3rd-party libraries which may have .NET framework requirements. I'll try to build with 4.5 now and let you know.

**Comment by SSE4** [comment]
no, unfortunately it's not so easy - Microsoft Visual Studio assemblies require 4.6.1. I think it depends on #75 where we can lower requirements.

**Comment by Gernatch** [comment]
@SSE4 That's okay. I'm finding that it's not that these guys don't have 4.6.1+ installed, they just have some projects built in 4.5. Had a miscommunication here. So this shouldn't be a problem because our minimum here is 4.6.2. On the whole I think 4.6.1 is a more than reasonable minimum.

**Comment by SSE4** [comment]
@Gernatch okay, good. I think we will create new update and let you know once it's published.

**Comment by jgsogo** [comment]
Thanks both of you for the work and the feedback  🙌 . I think it makes sense to release a new version `1.1.x` with the changes in #89 that are fixing this issue.
