### ISSUE TITLE
Create script to help in the release process

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-vs-extension#90]
It would be really nice to have a script that helps in the release process:

 0. Work only on `dev` branch
 1. Check for next release (or ask the user for the milestone)
 2. Get information about the milestone:
    + if there open PR, complain, we are not going to release if there is pending work
    + for every closed PR, get the `changelog` information
 3. Write changelog information into the `CHANGELOG` file (it should be a new entry)
 4. Modify version string (check it is greater than existing one)
 5. Commit these changes into `dev`
 6. Open release candidate branch `rc-<version>`
 7. Create PR to `master`

**Comment by SSE4** [comment]
are there existing solutions for this? e.g. how do you generate changelog automatically for conan right now?

**Comment by SSE4** [comment]
some additional steps:
- create tag in GitHub
- create release in GitHub
- publish artifacts (vsix, source code) into GitHub

**Comment by SSE4** [comment]
some bot to check: https://github.com/apps/conventional-release-bot

**Comment by jgsogo** [comment]
Yes, it is an option to publish only on tags, but my suggestion was to keep current _publish everything committed to master_ (every commit to master is a new release). Of course we can add something to make the commit, the tag and release in Github (related to https://github.com/conan-io/conan-vs-extension/pull/92#issuecomment-502607374), but I think that is the following step

**Comment by SSE4** [comment]
I think every push/merge creates new release, not every commit. without tags, it's hard to find points in history when releases were made, so I believe we should mark them, and yes, it's the following step - happens after merge/push to master.

**Comment by jgsogo** [comment]
To `master` branch there are only merges (ideally only from `dev`), commits without PR are forbidden.
