### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-vs-extension#99]
We need to start thinking about documenting those things that are stable. I'm not sure if it is a good idea to document the extension in the [Conan docs](https://docs.conan.io/en/latest/integrations/ide/visual_studio.html#conan-extension-for-visual-studio) or it is better to keep there just a reference and create a full _readthedocs_, GitHub pages,... in this repo.

The good thing is that in the MSFT marketplace there can only be one release, so there is no need to maintain the docs for several versions, a single branch like `doc` could be enough in this repo.

**Comment by jgsogo** [comment]
wdyt, @conan-io/barbarians ?

**Comment by SSE4** [comment]
is it possible to make doc more discoverable from the Visual Studio itself, e.g. by adding some submenu or whatever?

**Comment by danimtb** [comment]
We can consider using the wiki of this repo for the documentation
